#' @title cached_coding_genes.RData
#' @description  Gene symbols for all human protein coding genes, cached for use in vignettes. This data was generated by running load_all_protein_coding_symbols() from RITAN.
#' @format A \code{chr} vector of gene symbols for all protein coding genes
#' @source ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/locus_groups/protein-coding_gene.txt
#' @return Chr vector of gene symbols
#' @author Michael T Zimmermann
#' @examples
#' print(str(cached_coding_genes))
"cached_coding_genes"
